name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start containers
        run: docker compose up -d
      
      - name: Check running containers
        run: docker compose ps
        
      - name: View container logs
        run: docker compose logs
        
      - name: Test if FastAPI responds
        run: |
          sleep 3
          curl -I http://localhost:8000/health